/* eslint-disable @typescript-eslint/no-explicit-any */
import { Sale } from "@/types";

/**
 * Helper strictly designed to output the EXACT identical payload generated by
 * the physical 'Receipt Preview' button.
 * It takes `previewSale` directly if available (i.e. from the preview button),
 * otherwise it calculates it from `props` and `result` (i.e. from the submission).
 * It compiles it into a proper Sale object, and strictly caches it to `sessionStorage` 
 * so the preview display can decouple from `useSaleSubmit` without ever polluting `presentationSale`.
 */
export function cachePreviewSaleToSession(
  previewSale?: Sale | null,
  props?: any,
  result?: any
): void {
  try {
    let finalSaleToCache: Sale;

    if (previewSale) {
      finalSaleToCache = previewSale;
    } else if (props && result) {
      const formData = props.formData || {};
      
      // Resolve math exactly like handlePreview does
      const subtotal = formData.items?.reduce(
        (sum: number, i: any) => sum + Number(i.price || 0) * Number(i.quantity || 1),
        0
      ) || 0;
      
      const taxRate = Number(formData.taxRate || 0);
      const taxAmount = subtotal * (taxRate / 100);
      const total = subtotal + taxAmount;
    
      finalSaleToCache = {
        id: result?.id || "preview-session",
        receiptNumber: result?.receipt_number || result?.receiptNumber || "PREVIEW",
        customerName: formData.customerName || "Valued Customer",
        customerAddress: formData.customerAddress,
        customerContact: formData.customerContact,
        items: (formData.items || []).map((item: any) => ({
          ...item,
          price: Number(item.price || 0),
          quantity: Number(item.quantity || 1),
          total: Number(item.price || 0) * Number(item.quantity || 1),
        })) as any,
        paymentStatus: formData.paymentStatus,
        profit: 0,
        total: total,
        totalCost: 0,
        subtotal: subtotal,
        discount: 0,
        taxAmount: taxAmount,
        date: new Date(),
        taxRate: taxRate,
        createdAt: new Date(),
        updatedAt: new Date(),
        amountPaid: Number(formData.amountPaid || 0),
        amountDue: Number(formData.amountDue || 0),
      };
    } else {
      console.warn("No parameters provided to cachePreviewSaleToSession");
      return;
    }
  
    // Save to the browser's session storage native cache layer
    sessionStorage.setItem("last_completed_preview_sale", JSON.stringify(finalSaleToCache));
    console.log("Session preview successfully updated");
  } catch (err) {
    console.error("Failed to construct or save the preview session cache", err);
  }
}

